### How to creat on empty and a full numpy array

In [6]:
import numpy as np 
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
import numpy as np
arr= np.full([3, 3], 55, dtype=int)
arr

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

### Print full numpy array without truncation

In [11]:
import numpy as np
arr=np.array([1,2,3,45,6,3,])
arr

array([ 1,  2,  3, 45,  6,  3])

In [12]:
import numpy as np
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Numpy.full()in python

In [16]:
import numpy as np
arr= np.full([3, 3], 101.1, dtype=int)
arr


array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

In [1]:

import numpy as np 
arr=np.zeros((5,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import numpy as np 
arr=np.ones((5,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
import numpy as np 
arr=np.ones((5,2))
arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### How to remove rows in numpy array that contains non-numeric values

In [18]:

import numpy as np

n_arr = np.array([[10.5, 22.5, 3.8],
[41, np.nan, np.nan]])


print(n_arr)

print("\n Remove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])


[[10.5 22.5  3.8]
 [41.   nan  nan]]

 Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


### check whether a numpy array contains a specified row 

In [20]:

import numpy as np
arr = numpy.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])
print(arr)
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


### remove single-dimensional entries fron the shape of an array.

In [23]:


import numpy as np

in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])

print ("Input array : ", in_arr)
print("Shape of input array : ", in_arr.shape)

out_arr = np.squeeze(in_arr)

print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape)


Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


### Find the number of occurrences of a sequence in a NumPy array

In [28]:
import numpy
arr=numpy.array([[2,3,8,5],[8,4,7,5],[4,3,5,8]])
num=repr(arr).count("8")
num

3

### Find the most frequent value in a NumPy array

In [35]:
import numpy as np
x = np.array([23,54,23,67,98,34,23])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[23 54 23 67 98 34 23]
Most frequent value in the above array:
23
